# Generated by Django 4.2.2 on 2023-07-09 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updatedDate', models.DateTimeField(null=True, verbose_name='Updated date')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=20)),
                ('Post', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateTimeField(null=True, verbose_name='Date of Birth')),
                ('about', models.TextField()),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updatedDate', models.DateTimeField(null=True, verbose_name='Updated date')),
                ('IsActive', models.BooleanField(default=True)),
                ('IsManager', models.BooleanField(default=True)),
                ('contact', models.CharField(max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticket_des', models.TextField()),
                ('Ticket_subBy', models.CharField(max_length=50)),
                ('Ticket_type', models.CharField(max_length=30)),
                ('Ticket_urgency', models.CharField(max_length=30)),
                ('Ticket_openDate', models.DateField(auto_now_add=True, null=True, verbose_name='Open date')),
                ('Ticket_isApprove', models.BooleanField(default=False)),
                ('Ticket_isComplete', models.BooleanField(default=False)),
                ('Ticket_closedDate', models.DateField(null=True, verbose_name='Closed date')),
                ('Ticket_UpdatedDate', models.DateField(null=True, verbose_name='Updated date')),
                ('Ticket_assignTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employee')),
            ],
        ),
    ]
