# Generated by Django 4.2.2 on 2023-07-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Ticket_assignTo',
            field=models.CharField(max_length=100),
        ),
    ]
