# Generated by Django 4.2.2 on 2023-07-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_ticket_ticket_assignto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='Ticket_project',
            field=models.CharField(default='It Ticket', max_length=50),
            preserve_default=False,
        ),
    ]
