# Generated by Django 4.2.2 on 2023-07-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_employee_contact_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Ticket_isApprove',
            field=models.BooleanField(blank=True, default=None),
        ),
    ]
